title: Sifat Moonjerin
email: moonjerin.sifat@gmail.com
resume: https://drive.google.com/file/d/1ZqzDRJkyEefrP9x2HzYReLMphzW6CDbk/view
description: >- # this means to ignore newlines until "baseurl:"
  Sifat's personal blog.
url: "https://sifatmoonjerin.github.io"
permalink: /:categories/:title:output_ext
github_username:  sifatmoonjerin
linkedin_username: sifatmoonjerin

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
